# Generated by Django 2.2.2 on 2020-05-25 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('stop_time', models.TimeField()),
                ('no_of_buy_in', models.IntegerField()),
                ('no_of_pick_up', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pickup', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('notification', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Slot')),
            ],
        ),
    ]
