# Generated by Django 2.1.8 on 2020-05-29 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('shop_name', models.CharField(max_length=60)),
                ('owner_name', models.CharField(max_length=120)),
                ('ph_number', models.CharField(max_length=10, unique=True, verbose_name='Phone Number')),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuyInBooking',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(max_length=16, null=True, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PickUpBooking',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('user_id', models.CharField(max_length=16, null=True, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=256)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slot_id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('num_pickups', models.IntegerField(default=0)),
                ('num_buyins', models.IntegerField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
