# Generated by Django 3.0.6 on 2020-05-25 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200525_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_In',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('no_of_buyin', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pick_Up',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('no_of_pickup', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='buy_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Buy_In'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pick_up',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Pick_Up'),
        ),
    ]
