# Generated by Django 3.0.6 on 2020-05-25 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200525_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='buy_in',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Buy_In'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pick_up',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Pick_Up'),
        ),
    ]
