# Generated by Django 3.0.6 on 2020-05-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200525_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='no_of_buy_in',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='no_of_pick_up',
        ),
    ]
